version: '3.8'

services:
  uzima-ai-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data  # Mount data directory if you have additional data files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - uzima-network

  # Optional: Add a reverse proxy (nginx) for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - uzima-ai-api
    restart: unless-stopped
    networks:
      - uzima-network

networks:
  uzima-network:
    driver: bridge
