services:
  - type: web
    name: uzima-ai-api
    env: python
    plan: free
    buildCommand: ./build-simple.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
